[package]
name = "luau-src"
version = "0.1.0"
edition = "2021"
build = "build.rs"
description = "Luau source code bindings"
license = "MIT"

[lib]
crate-type = ["lib"]

[dependencies]

[build-dependencies]
walkdir = "2.3.2"
bindgen = "0.59.1"
cc = "1.0.71"

[features]
default = []
no-link = []