[package]
name = "luau"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]

[build-dependencies]
walkdir = "2.3.2"
bindgen = "0.59.1"
cc = "1.0.71"

[features]
default = []
no-link = []